### ISSUE TITLE
Intall solr/haystack component

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/mia-councilmatic#18]
## On Digital Ocean

(Taken from notes at https://github.com/datamade/chi-councilmatic)
- [x] `sudo apt-get update` on unbuntu
- [x] `sudo apt-get install openjdk-7-jre-headless` on unbuntu
- [x] Download & setup Solr:
  - [x] `wget http://mirror.sdunix.com/apache/lucene/solr/4.10.4/solr-4.10.4.tgz`
  - [x] `tar -xvf solr-4.10.4.tgz`
  - [x] `sudo cp -R solr-4.10.4/example /opt/solr`
  - [x] `sudo cp solr_scripts/schema.xml /opt/solr/example/solr/collection1/conf/schema.xml`
- [x] Run Solr:
  - [x] `cd /opt/solr/example; sudo java -jar start.jar`
- [ ] Index the database
  - [ ] `python manage.py rebuild_index` in councilmatic directory
- [ ] Install and configure Jetty for Solr
- [ ] Regenerate Solr schema

**Comment by ErnieAtLYD** [comment]
```
(venv) codeformiami@mia-Councilmatic:~/Dropbox/mia-councilmatic$ python manage.py rebuild_index

WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N] y
Removing all documents from your index because you said so.
Traceback (most recent call last):
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/pysolr.py", line 411, in _extract_error
    reason = resp.json()['error']['msg']
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/haystack/management/commands/rebuild_index.py", line 25, in handle
    call_command('clear_index', **options)
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/haystack/management/commands/clear_index.py", line 56, in handle
    backend.clear(commit=self.commit)
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/haystack/backends/solr_backend.py", line 101, in clear
    self.conn.delete(q='*:*', commit=commit)
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/pysolr.py", line 844, in delete
    return self._update(m, commit=commit, waitFlush=waitFlush, waitSearcher=waitSearcher)
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/pysolr.py", line 399, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/pysolr.py", line 328, in _send_request
    error_message = self._extract_error(resp)
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/pysolr.py", line 417, in _extract_error
    reason, full_html = self._scrape_response(resp.headers, resp.content)
  File "/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/pysolr.py", line 445, in _scrape_response
    if response.startswith('<?xml'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by ErnieAtLYD** [comment]
Ergh, never mind. I had solr running on a different tab - if I `Control+Z` on the tab running `solr` and run the rebuilding command I get the following:

```
(venv) codeformiami@mia-Councilmatic:~/Dropbox/mia-councilmatic$ python manage.py rebuild_index

WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N] y
Removing all documents from your index because you said so.
Failed to clear Solr index: Connection to server 'http://127.0.0.1:8983/solr/chicago/update/?commit=true' timed out: HTTPConnectionPool(host='127.0.0.1', port=8983): Read timed out. (read timeout=10)
All documents removed.
Indexing 3644 chicago bills
Failed to add documents to Solr: Connection to server 'http://127.0.0.1:8983/solr/chicago/update/?commit=true' timed out: HTTPConnectionPool(host='127.0.0.1', port=8983): Read timed out. (read timeout=10)
```

But now I don't know what to do next...
